
'use server';

import { db } from '@/lib/firebase';
import { collection, addDoc, serverTimestamp, Timestamp } from 'firebase/firestore';

export interface ReelData {
  id: string;
  userId: string;
  creatorName?: string;
  creatorAvatarUrl?: string | null;
  videoUrl: string; // Primary display video URL (could be a transcoded version)
  videoUrlOriginal?: string; // URL of the original uploaded video
  videoThumbnailUrl?: string; // URL for a thumbnail generated by Resize Images or another process
  dataAiHintVideo?: string;
  caption?: string;
  tags?: string[];
  viewCount?: number;
  likeCount?: number;
  commentCount?: number;
  isPublished?: boolean;
  createdAt: Timestamp;
  updatedAt: Timestamp;
  moderationStatus?: 'pending' | 'approved' | 'rejected' | 'escalated';
  moderationInfo?: {
    checkedAt?: Timestamp;
    reason?: string;
    autoModerated?: boolean;
  };
}

export async function createReel(
  userId: string,
  creatorName: string | null | undefined,
  creatorAvatarUrl: string | null | undefined,
  reelDetails: Omit<ReelData, 'id' | 'userId' | 'creatorName' | 'creatorAvatarUrl' | 'createdAt' | 'updatedAt' | 'viewCount' | 'likeCount' | 'commentCount' | 'isPublished' | 'moderationStatus' | 'moderationInfo' | 'videoUrlOriginal' | 'videoThumbnailUrl'> & { videoUrlOriginal?: string; videoThumbnailUrl?: string; }
): Promise<{ success: boolean; reelId?: string; message?: string }> {
  if (!userId) {
    const msg = '[createReel] Missing userId.';
    console.warn(msg);
    return { success: false, message: "User ID is required to create a reel." };
  }
  if (!reelDetails.videoUrl) {
    const msg = `[createReel] Missing videoUrl for userId: ${userId}`;
    console.warn(msg);
    return { success: false, message: "Video URL is required." };
  }
  console.info(`[createReel] Attempting for userId: ${userId}`);

  try {
    const reelsCollectionRef = collection(db, 'reels');
    
    const docRef = await addDoc(reelsCollectionRef, {
      ...reelDetails,
      userId,
      creatorName: creatorName || "Charisarthub Artist",
      creatorAvatarUrl: creatorAvatarUrl || null,
      videoUrlOriginal: reelDetails.videoUrlOriginal || reelDetails.videoUrl, // Store original if provided, else fallback to main
      videoThumbnailUrl: reelDetails.videoThumbnailUrl || null, // Store thumbnail if provided
      viewCount: 0,
      likeCount: 0,
      commentCount: 0,
      isPublished: true,
      moderationStatus: 'pending',
      moderationInfo: null,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    });
    console.info(`[createReel] Successfully created reelId: ${docRef.id} for userId: ${userId}. Moderation status: pending.`);
    // TODO: Trigger content moderation Cloud Function here for the new reel (docRef.id)
    return { success: true, reelId: docRef.id };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : "An unknown error occurred.";
    console.error(`[createReel] Error for userId: ${userId}: ${errorMessage}`, error);
    return { success: false, message: `Failed to create reel: ${errorMessage}` };
  }
}

    