
"use client"; // Required for Recharts client-side rendering

import React from 'react'; // Import React
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { BarChartBig, Zap, Users, TrendingUp, Percent, ShieldCheck, Info } from "lucide-react";
import Image from "next/image";
import { ChartTooltip, ChartTooltipContent, ChartContainer, ChartLegend, ChartLegendContent } from '@/components/ui/chart';
import { Bar, BarChart as RechartsBarChart, CartesianGrid, XAxis, YAxis, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";


// --- MOCK DATA ---
// In a real application, this data would be fetched from the backend,
// where it would be aggregated by Firebase Cloud Functions or similar server-side processes.
const attentionData = [
  { source: 'Crystalline Blooms', attention: 45, fill: 'hsl(var(--chart-1))' },
  { source: 'Flux Signature Profile', attention: 30, fill: 'hsl(var(--chart-2))' },
  { source: 'Biome Posts', attention: 15, fill: 'hsl(var(--chart-3))' },
  { source: 'Shop Links', attention: 10, fill: 'hsl(var(--chart-4))' },
];

const growthData = [
  { month: 'Jan', growth: 10 },
  { month: 'Feb', growth: 15 },
  { month: 'Mar', growth: 12 },
  { month: 'Apr', growth: 20 },
  { month: 'May', growth: 25 },
  { month: 'Jun', growth: 30 },
];

const chartConfig = {
  attention: {
    label: "Attention",
  },
  growth: {
    label: "Growth Velocity",
    color: "hsl(var(--primary))",
  }
} satisfies import("@/components/ui/chart").ChartConfig;
// --- END MOCK DATA ---


export default function InsightsPage() {
  return (
    <div className="space-y-8">
      <Card className="shadow-lg card-interactive-hover">
        <CardHeader className="text-center">
          <BarChartBig className="mx-auto h-12 w-12 text-primary mb-2" />
          <CardTitle className="text-3xl text-gradient-primary-accent">Energy Flow Patterns</CardTitle>
          <p className="text-xs text-muted-foreground mt-1">Created by Charis</p>
          <CardDescription>Analyze attention pooling and network growth velocity around your Flux Signature and Private Biomes.</CardDescription>
        </CardHeader>
      </Card>

       <Alert variant="default" className="bg-primary/10 border-primary/30">
          <Info className="h-5 w-5 text-primary" />
          <AlertTitle className="text-primary">Placeholder Data</AlertTitle>
          <AlertDescription>
            The data and charts currently displayed on this page are for demonstration purposes only.
            In a live application, this information would be dynamically generated by backend processes
            analyzing your actual activity and engagement on Charis Art Hub.
          </AlertDescription>
        </Alert>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card className="card-interactive-hover">
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><Zap className="h-5 w-5 text-accent" /> Attention Pooling</CardTitle>
            <CardDescription>Where your audience's attention is currently focused (Mock Data).</CardDescription>
          </CardHeader>
          <CardContent>
            {/* 
              Backend Task for "Attention Pooling":
              - A scheduled Firebase Cloud Function would analyze interaction data:
                - Views on different Crystalline Bloom types (artwork, sketch, process).
                - Views on Flux Signature profiles.
                - Activity within Biomes (e.g., post views, comments).
                - Clicks on shop links from Material Origin Links.
              - This data would be aggregated periodically (e.g., daily/weekly) and stored in a user-specific
                document in Firestore (e.g., /users/{userId}/insights/attention).
              - This page would then fetch and display this aggregated data.
            */}
            <ChartContainer config={chartConfig} className="h-[300px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <ChartTooltip content={<ChartTooltipContent hideLabel />} />
                  <Pie data={attentionData} dataKey="attention" nameKey="source" cx="50%" cy="50%" outerRadius={100} label>
                     {attentionData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.fill} />
                      ))}
                  </Pie>
                  <ChartLegend content={<ChartLegendContent />} />
                </PieChart>
              </ResponsiveContainer>
            </ChartContainer>
          </CardContent>
        </Card>

        <Card className="card-interactive-hover">
          <CardHeader>
            <CardTitle className="flex items-center gap-2"><TrendingUp className="h-5 w-5 text-accent" /> Network Growth Velocity</CardTitle>
            <CardDescription>How quickly your connected network is expanding (Mock Data).</CardDescription>
          </CardHeader>
          <CardContent>
            {/*
              Backend Task for "Network Growth Velocity":
              - A scheduled Firebase Cloud Function would analyze:
                - New followers over time (e.g., daily/weekly changes in followersCount on UserProfileData).
                - New members joining the user's Biomes.
                - Growth in interactions on user's content.
              - This velocity data would be aggregated (e.g., monthly growth percentages) and stored in Firestore.
              - This page would fetch and display this time-series growth data.
            */}
             <ChartContainer config={chartConfig} className="h-[300px] w-full">
              <RechartsBarChart data={growthData} accessibilityLayer>
                <CartesianGrid vertical={false} />
                <XAxis dataKey="month" tickLine={false} tickMargin={10} axisLine={false} />
                <YAxis />
                <ChartTooltip content={<ChartTooltipContent indicator="dashed" />} />
                <Bar dataKey="growth" fill="var(--color-growth)" radius={4} />
              </RechartsBarChart>
            </ChartContainer>
          </CardContent>
        </Card>
      </div>
      
      <Card className="card-interactive-hover">
        <CardHeader>
            <CardTitle>Key Metrics (Mock Data)</CardTitle>
        </CardHeader>
        <CardContent className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {/*
              Backend Task for "Key Metrics":
              - These would be derived from UserProfileData (followersCount), BiomeData (memberCount for owned biomes),
                and aggregated interaction data (e.g., total artwork views, engagement rate calculated from likes/comments/views).
              - Some metrics might be directly available (followersCount), others would require calculation by Cloud Functions.
            */}
            <div className="p-4 bg-muted/50 rounded-lg">
                <div className="flex items-center text-sm text-muted-foreground"><Users className="h-4 w-4 mr-1" /> Followers</div>
                <div className="text-2xl font-bold">1,234</div>
                <div className="text-xs text-green-500 flex items-center"><TrendingUp className="h-3 w-3 mr-0.5" /> +5% last month</div>
            </div>
             <div className="p-4 bg-muted/50 rounded-lg">
                <div className="flex items-center text-sm text-muted-foreground"><Percent className="h-4 w-4 mr-1" /> Engagement Rate</div>
                <div className="text-2xl font-bold">7.8%</div>
                <div className="text-xs text-green-500 flex items-center"><TrendingUp className="h-3 w-3 mr-0.5" /> +0.5% last week</div>
            </div>
            <div className="p-4 bg-muted/50 rounded-lg">
                <div className="flex items-center text-sm text-muted-foreground"><Zap className="h-4 w-4 mr-1" /> Bloom Views</div>
                <div className="text-2xl font-bold">10.5K</div>
                <div className="text-xs text-muted-foreground">Past 30 days</div>
            </div>
             <div className="p-4 bg-muted/50 rounded-lg">
                <div className="flex items-center text-sm text-muted-foreground"><ShieldCheck className="h-4 w-4 mr-1" /> Biome Members</div>
                <div className="text-2xl font-bold">88</div>
                <div className="text-xs text-green-500 flex items-center"><TrendingUp className="h-3 w-3 mr-0.5" /> +12 this month</div>
            </div>
        </CardContent>
      </Card>

      <Card className="card-interactive-hover">
        <CardHeader>
          <CardTitle>Detailed Energy Flow Visualization (Conceptual)</CardTitle>
          <CardDescription>An interactive map showing connections and energy intensity. (Conceptual - requires significant backend data processing)</CardDescription>
        </CardHeader>
        <CardContent className="text-center">
          {/*
            Backend Task for "Detailed Energy Flow Visualization":
            - This is the most complex. It would require:
              - Tracking various types of interactions between users, artworks, and biomes.
              - Analyzing these interactions to determine "energy" or "attention" flow.
              - Storing this complex graph-like data in a way that's queryable for visualization
                (Firestore might be challenging for this at scale; a graph database or specialized
                 data store might be considered for a very advanced version).
              - Providing an API or server actions to feed data to a frontend graph visualization library.
          */}
          <Image src="https://placehold.co/800x450.png" alt="Energy Flow Visualization Placeholder" width={800} height={450} className="rounded-md object-cover mx-auto" data-ai-hint="network graph" />
          <p className="mt-2 text-sm text-muted-foreground">This area will feature a dynamic, interactive graph visualizing the energy flow patterns once backend aggregation is implemented.</p>
        </CardContent>
      </Card>
    </div>
  );
}
